inherit_from:
  - .rubocop_todo.yml

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さないを無効
Documentation:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

### .rubocop_todoより移行
# Offense count: 45
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/HashAlignment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

# Offense count: 3
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 50

# Offense count: 29
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 200

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 109

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 21

# Offense count: 3
Security/Open:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'config/puma.rb'

# Offense count: 78
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/rails_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Exclude:
    - 'Gemfile'

CyclomaticComplexity:
  Max: 9

PerceivedComplexity:
   Max: 9