default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: bike_app_development

test:
  <<: *default
  database: bike_app_test

production:
  <<: *default
  database: bike_app_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock





# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   host: db

# development:
#   <<: *default
#   username: hogehoge
#   password: fasjkdl29
#   database: docker_development

# production:
#   <<: *default
#   database: docker_production
#   username: docker
#   password: <%= ENV['DOCKER_DATABASE_PASSWORD'] %>
